
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
public partial struct Pos
{
    
    public Pos(ByteBuf _buf) 
    {
        X = _buf.ReadFloat();
        Y = _buf.ReadFloat();
    }

    public static Pos DeserializePos(ByteBuf _buf)
    {
        return new Pos(_buf);
    }

    /// <summary>
    /// X轴
    /// </summary>
    public float X;
    /// <summary>
    /// Y轴
    /// </summary>
    public float Y;


    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref Pos other)
    {
        other.X = X;
        other.Y = Y;
    }
    
    public override string ToString()
    {
        return "{ "
        + "X:" + X + ","
        + "Y:" + Y + ","
        + "}";
    }
}
}

